name: fl
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2024.9.24
  - libffi=3.4.4
  - ncurses=6.4
  - openssl=3.0.15
  - pip=24.2
  - python=3.10.15
  - readline=8.2
  - setuptools=75.1.0
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
    - aiohappyeyeballs==2.4.3
    - aiohttp==3.11.7
    - aiosignal==1.3.1
    - async-timeout==5.0.1
    - attrs==24.2.0
    - certifi==2024.8.30
    - cffi==1.17.1
    - charset-normalizer==3.4.0
    - click==8.1.7
    - contourpy==1.3.1
    - cryptography==42.0.8
    - cycler==0.12.1
    - datasets==3.1.0
    - dill==0.3.8
    - filelock==3.16.1
    - flwr==1.13.0
    - flwr-datasets==0.4.0
    - fonttools==4.55.0
    - frozenlist==1.5.0
    - fsspec==2024.9.0
    - grpcio==1.64.3
    - hatchling==1.26.3
    - huggingface-hub==0.26.2
    - idna==3.10
    - iterators==0.0.2
    - jinja2==3.1.4
    - kiwisolver==1.4.7
    - markdown-it-py==3.0.0
    - markupsafe==3.0.2
    - matplotlib==3.9.2
    - mdurl==0.1.2
    - mpmath==1.3.0
    - multidict==6.1.0
    - multiprocess==0.70.16
    - networkx==3.4.2
    - numpy==1.26.4
    - packaging==24.2
    - pandas==2.2.3
    - pathspec==0.12.1
    - pillow==11.0.0
    - pluggy==1.5.0
    - propcache==0.2.0
    - protobuf==4.25.5
    - pyarrow==16.1.0
    - pycparser==2.22
    - pycryptodome==3.21.0
    - pygments==2.18.0
    - pyparsing==3.2.0
    - python-dateutil==2.9.0.post0
    - pytz==2024.2
    - pyyaml==6.0.2
    - requests==2.32.3
    - rich==13.9.4
    - seaborn==0.13.2
    - shellingham==1.5.4
    - six==1.16.0
    - sympy==1.13.1
    - tomli==2.1.0
    - tomli-w==1.1.0
    - torch==2.5.1
    - tqdm==4.67.0
    - trove-classifiers==2024.10.21.16
    - typer==0.12.5
    - typing-extensions==4.12.2
    - tzdata==2024.2
    - urllib3==2.2.3
    - xxhash==3.5.0
    - yarl==1.18.0
